bring back wait for minio; deleted by accident

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -39,7 +39,19 @@ runs:
           exit 1
         fi
 
-
+    - name: Wait for MinIO
+      shell: bash
+      run: |
+        for i in {1..10}; do
+          if curl --max-time 10 -fs http://127.0.0.1:9001/minio/health/live; then
+            echo "MinIO is up!"
+            exit 0
+          fi
+          echo "Waiting for MinIO to be ready... Attempt $i"
+          sleep 10
+        done
+        echo "Failed to connect to MinIO after 10 attempts."
+        exit 1
 
     - name: Run tests that don't require secrets
       shell: bash
