add codecov (#127)
- generate coverage metrics from pytest
- add a codecov upload
- this is done outside of the composite action so integration tests from
the nabu repo don't generate code coverage outputs for scheduler
- fix pyright to use uv
- commit history is kind of messy since it took me a sec to get the
composite action paths working

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,4 +64,16 @@ runs:
         python -m venv .venv
         source .venv/bin/activate
         pip install -r requirements.txt
-        GLEANER_IMAGE="${{ inputs.gleaner_image }}" NABU_IMAGE="${{ inputs.nabu_image }}" pytest -x -vv
+        GLEANER_IMAGE="${{ inputs.gleaner_image }}" NABU_IMAGE="${{ inputs.nabu_image }}" pytest -x -vv --cov-branch --cov-report=xml --cov
+        if [ ! -f coverage.xml ]; then
+          echo "Coverage report not found!"
+          exit 1
+        fi
+        echo "Absolute path of coverage.xml: $(realpath coverage.xml)"
+
+    - name: Archive code coverage results
+      uses: actions/upload-artifact@v4
+      with:
+        name: scheduler-code-coverage-report
+        path: coverage.xml
+        if-no-files-found: error
