path check

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -65,6 +65,11 @@ runs:
         source .venv/bin/activate
         pip install -r requirements.txt
         GLEANER_IMAGE="${{ inputs.gleaner_image }}" NABU_IMAGE="${{ inputs.nabu_image }}" pytest -x -vv --cov-branch --cov-report=xml
+        if [ ! -f coverage.xml ]; then
+          echo "Coverage report not found!"
+          exit 1
+        fi
+
 
     - name: Archive code coverage results
       uses: actions/upload-artifact@v4
